use colored::*;
use std::env;
use std::path::PathBuf;
use std::process::Command;

pub fn launch_native_desktop_window() {
    println!("{}", "\n🖥️ --- [NANTARA NATIVE DESKTOP WINDOW ENGINE v2.0] ---".cyan().bold());

    let mut found_path: Option<PathBuf> = None;

    // Check Candidate 1: Direct working directory
    let p1 = PathBuf::from("web/index.html");
    if p1.exists() {
        found_path = Some(p1);
    } else if let Ok(exe_path) = env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            // Candidate 2: target/debug -> ../../web/index.html
            let p2 = exe_dir.join("../../web/index.html");
            if p2.exists() {
                found_path = Some(p2);
            } else {
                // Candidate 3: root level -> src/launcher/web/index.html
                let p3 = exe_dir.join("../../../src/launcher/web/index.html");
                if p3.exists() {
                    found_path = Some(p3);
                }
            }
        }
    }

    if let Some(target_file) = found_path {
        // Strip UNC prefix \\?\ if generated by canonicalize on Windows
        let abs_str = std::fs::canonicalize(&target_file)
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_else(|_| target_file.to_string_lossy().to_string());
        
        let clean_path = abs_str.trim_start_matches(r"\\?\").replace("\\", "/");
        let file_url = format!("file:///{}", clean_path);

        println!("  -> Target UI Path : {}", file_url.green());
        println!("  -> Window Mode   : Standalone App Window Container");

        // 1. Launch in Standalone App Window mode via Microsoft Edge App Mode
        let _ = Command::new("cmd")
            .args([
                "/c",
                "start",
                "msedge",
                &format!("--app={}", file_url),
                "--window-size=1280,800"
            ])
            .spawn();

        // 2. Backup Fallback: Open URL directly in default system browser
        let _ = Command::new("cmd")
            .args(["/c", "start", "", &file_url])
            .spawn();

        println!("{}", "  ✅ Native Desktop Window Launched Successfully!".green().bold());
    } else {
        println!("{}", "  ⚠️ Warning: Web UI assets (web/index.html) not found in path.".yellow());
    }

    println!("{}", "--------------------------------------------------".dimmed());
}
